export interface Cliente {
    id: number
    nome: string
    conjuge: string
    estado_civil: string
    local_nascimento: string
    cpf: string
    cnpj: string
    rg: string
    data_emissao: number
    uf_identidade: string
    data_nascimento: string
    pai: string
    mae: string
    telefone: string
    celular: string
    residencia: string
    tempo_residencia: string
    nome_referencia_pessoal1: string
    telefone_referencia_pessoal1: string
    nome_referencia_pessoal2: string
    telefone_referencia_pessoal2: string
    nome_referencia_comercial1: string
    telefone_referencia_comercial1: string
    nome_referencia_comercial2: string
    telefone_referencia_comercial2: string
    empresa: string
    empresa_cnpj: string
    data_inicio: number
    cbo: string
    endereco_empresa: string
    telefone_empresa: string
    cidade_empresa: string
    uf_empresa: string
    cep_empresa: string
    cargo: string
    salario: string
    outras_rendas: string
    observacoes: string
    nacionalidade: string
    id_usuario: number
    data_cadastro: number
  }